spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
    platform: postgres
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api
docker-secret:
  bind-path: /run/secrets
senior-project:
  app:
    jwtSecret: ${JWT_SECRET}
