spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: env.properties
  datasource:
    url: 'jdbc:postgresql://${DB_HOST}.${DB_HOST_URL}:${DB_PORT}/${DB_NAME}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
    platform: postgres
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 895369180669-428hds3bpk7muithstgfdu9spqq0gd75.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
# This Datasource is for production build online
'#spring':
  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}'
docker-secret:
  bind-path: /run/secrets
